import { count } from "drizzle-orm";
import { db } from "@/db";
import { menuItems, reviews } from "@/db/schema";

export const catalog = [
  {
    slug: "aureum-latte",
    name: "Aureum Latte",
    description: "Our signature double espresso stretched with steamed milk and a velvet microfoam finish.",
    category: "espresso",
    priceCents: 650,
    imageUrl: "/images/latte.png",
    featured: true,
    available: true,
    tag: "Signature",
    ingredients: "Espresso, Whole Milk",
    allergens: "Dairy",
    milkOptions: "Whole, Oat, Almond",
    temperatureOptions: "Hot, Iced",
    sweetnessLevel: "Low",
    coffeeStrength: "Medium",
    isDairyFree: false,
    isGlutenFree: true,
  },
  {
    slug: "single-origin-espresso",
    name: "Single Origin Espresso",
    description: "A concentrated pour of rotating estate beans with cocoa, citrus, and a long sweet finish.",
    category: "espresso",
    priceCents: 400,
    imageUrl: "/images/espresso.png",
    featured: true,
    available: true,
    tag: "House",
    ingredients: "Espresso",
    allergens: "None",
    milkOptions: "None",
    temperatureOptions: "Hot",
    sweetnessLevel: "None",
    coffeeStrength: "Strong",
    isDairyFree: true,
    isGlutenFree: true,
  },
  {
    slug: "flat-white",
    name: "Flat White",
    description: "Ristretto shots folded into silk milk. Compact, glossy, and precisely balanced.",
    category: "espresso",
    priceCents: 550,
    imageUrl: "/images/flatwhite.png",
    featured: false,
    available: true,
    tag: null,
    ingredients: "Ristretto Espresso, Whole Milk",
    allergens: "Dairy",
    milkOptions: "Whole, Oat, Almond",
    temperatureOptions: "Hot, Iced",
    sweetnessLevel: "None",
    coffeeStrength: "Strong",
    isDairyFree: false,
    isGlutenFree: true,
  },
  {
    slug: "dark-mocha",
    name: "Dark Mocha",
    description: "70% single-origin chocolate melted into espresso and finished with a thin cream cap.",
    category: "espresso",
    priceCents: 675,
    imageUrl: "/images/mocha.png",
    featured: false,
    available: true,
    tag: null,
    ingredients: "Espresso, 70% Dark Chocolate, Whole Milk",
    allergens: "Dairy",
    milkOptions: "Whole, Oat, Almond",
    temperatureOptions: "Hot, Iced",
    sweetnessLevel: "Medium",
    coffeeStrength: "Medium",
    isDairyFree: false,
    isGlutenFree: true,
  },
  {
    slug: "yirgacheffe-pourover",
    name: "Yirgacheffe Pour-Over",
    description: "Floral Ethiopian lot brewed to order. Bergamot, wild honey, and jasmine on the nose.",
    category: "brew",
    priceCents: 700,
    imageUrl: "https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=800&q=80&auto=format&fit=crop",
    featured: true,
    available: true,
    tag: "Origin",
    ingredients: "Ethiopian Yirgacheffe Coffee Beans, Water",
    allergens: "None",
    milkOptions: "None",
    temperatureOptions: "Hot",
    sweetnessLevel: "None",
    coffeeStrength: "Mild",
    isDairyFree: true,
    isGlutenFree: true,
  },
  {
    slug: "house-cold-brew",
    name: "House Cold Brew",
    description: "Eighteen-hour steep. Low acid, dark cherry sweetness, served over a single clear cube.",
    category: "brew",
    priceCents: 575,
    imageUrl: "https://images.unsplash.com/photo-1461023058943-07fcbe16d735?w=800&q=80&auto=format&fit=crop",
    featured: true,
    available: true,
    tag: "All day",
    ingredients: "House Blend Coffee Beans, Filtered Water",
    allergens: "None",
    milkOptions: "Whole, Oat, Almond",
    temperatureOptions: "Iced",
    sweetnessLevel: "None",
    coffeeStrength: "Strong",
    isDairyFree: true,
    isGlutenFree: true,
  },
  {
    slug: "tasting-flight",
    name: "Tasting Flight",
    description: "Three 3oz pours of the current espresso, filter, and seasonal lot with tasting notes.",
    category: "brew",
    priceCents: 1400,
    imageUrl: "https://images.unsplash.com/photo-1507133750040-4a8f57021571?w=800&q=80&auto=format&fit=crop",
    featured: false,
    available: true,
    tag: "For two",
    ingredients: "Various Coffee Beans, Water",
    allergens: "None",
    milkOptions: "None",
    temperatureOptions: "Hot, Iced",
    sweetnessLevel: "None",
    coffeeStrength: "Various",
    isDairyFree: true,
    isGlutenFree: true,
  },
  {
    slug: "ceremonial-matcha",
    name: "Ceremonial Matcha",
    description: "Stone-milled Uji matcha whisked to a fine foam. Bright, savory, and quietly sweet.",
    category: "seasonal",
    priceCents: 625,
    imageUrl: "https://images.unsplash.com/photo-1515823064-d6e0c04616a7?w=800&q=80&auto=format&fit=crop",
    featured: false,
    available: true,
    tag: "Seasonal",
    ingredients: "Ceremonial Uji Matcha, Water, Optional Milk",
    allergens: "None",
    milkOptions: "Whole, Oat, Almond",
    temperatureOptions: "Hot, Iced",
    sweetnessLevel: "Low",
    coffeeStrength: "None",
    isDairyFree: true,
    isGlutenFree: true,
  },
  {
    slug: "affogato",
    name: "Affogato",
    description: "Madagascar vanilla gelato drowned in a hot espresso. Dessert and digestif in one glass.",
    category: "seasonal",
    priceCents: 750,
    imageUrl: "https://images.unsplash.com/photo-1579954115545-a95591f28bfc?w=800&q=80&auto=format&fit=crop",
    featured: false,
    available: true,
    tag: "Dessert",
    ingredients: "Espresso, Madagascar Vanilla Gelato",
    allergens: "Dairy",
    milkOptions: "None",
    temperatureOptions: "Hot and Cold",
    sweetnessLevel: "High",
    coffeeStrength: "Strong",
    isDairyFree: false,
    isGlutenFree: true,
  },
  {
    slug: "butter-croissant",
    name: "Butter Croissant",
    description: "Laminated overnight with French butter. Shattering exterior, honeyed crumb.",
    category: "kitchen",
    priceCents: 450,
    imageUrl: "/images/butter_croissant.jpg",
    featured: false,
    available: true,
    tag: "Baked at 6am",
    ingredients: "Wheat Flour, Butter, Yeast, Salt, Sugar",
    allergens: "Dairy, Wheat, Gluten",
    milkOptions: "None",
    temperatureOptions: "None",
    sweetnessLevel: "Low",
    coffeeStrength: "None",
    isDairyFree: false,
    isGlutenFree: false,
  },
  {
    slug: "chocolate-morning-bun",
    name: "Chocolate Morning Bun",
    description: "A coiled bun of dark chocolate, orange zest, and toasted sugar. Made for the first coffee.",
    category: "kitchen",
    priceCents: 525,
    imageUrl: "/images/chocolate_morning_bun.jpg",
    featured: false,
    available: true,
    tag: null,
    ingredients: "Wheat Flour, Butter, Dark Chocolate, Orange Zest, Sugar, Yeast",
    allergens: "Dairy, Wheat, Gluten",
    milkOptions: "None",
    temperatureOptions: "None",
    sweetnessLevel: "Medium",
    coffeeStrength: "None",
    isDairyFree: false,
    isGlutenFree: false,
  },
  {
    slug: "corner-table-set",
    name: "Corner Table Set",
    description: "Aureum latte, butter croissant, and still water. The weekday ritual, composed.",
    category: "kitchen",
    priceCents: 1200,
    imageUrl: "/images/corner_table_set.jpg",
    featured: false,
    available: true,
    tag: "Set",
    ingredients: "Aureum Latte, Butter Croissant, Water",
    allergens: "Dairy, Wheat, Gluten",
    milkOptions: "Whole, Oat, Almond",
    temperatureOptions: "Hot, Iced",
    sweetnessLevel: "Low",
    coffeeStrength: "Medium",
    isDairyFree: false,
    isGlutenFree: false,
  },
];

const seedReviews = [
  {
    customerName: "Alice W.",
    rating: 5,
    comment: "The Aureum Latte is incredible. Silky and perfect temperature.",
    category: "taste",
  },
  {
    customerName: "Mark T.",
    rating: 4,
    comment: "Great quality beans, but the cold brew was a little too strong for me.",
    category: "quality",
  },
  {
    customerName: "Sarah J.",
    rating: 5,
    comment: "Barista was super friendly and helped me pick the right matcha.",
    category: "service",
  },
  {
    customerName: "David L.",
    rating: 3,
    comment: "A bit pricey for a daily coffee, but good for a treat.",
    category: "price",
  },
  {
    customerName: "Emily R.",
    rating: 4,
    comment: "Waited 15 minutes for a pour-over. Worth it, but keep it in mind if you're in a rush.",
    category: "waiting_time",
  },
  {
    customerName: "John D.",
    rating: 5,
    comment: "Impeccably clean space. Loved sitting by the window.",
    category: "cleanliness",
  },
  {
    customerName: "Michael B.",
    rating: 5,
    comment: "Best croissant I've had outside of Paris.",
    category: "taste",
  },
];

export async function ensureMenuSeeded() {
  const [existingItems] = await db.select({ value: count() }).from(menuItems);
  if ((existingItems?.value ?? 0) === 0) {
    await db.insert(menuItems).values(catalog);
  }

  const [existingReviews] = await db.select({ value: count() }).from(reviews);
  if ((existingReviews?.value ?? 0) === 0) {
    await db.insert(reviews).values(seedReviews);
  }
}
