import { count } from "drizzle-orm";
import { db } from "@/db";
import { menuItems } from "@/db/schema";

export const catalog = [
  {
    slug: "aureum-latte",
    name: "Aureum Latte",
    description: "Our signature double espresso stretched with steamed milk and a velvet microfoam finish.",
    category: "espresso",
    priceCents: 650,
    imageUrl: "/images/latte.png",
    featured: true,
    available: true,
    tag: "Signature",
  },
  {
    slug: "single-origin-espresso",
    name: "Single Origin Espresso",
    description: "A concentrated pour of rotating estate beans with cocoa, citrus, and a long sweet finish.",
    category: "espresso",
    priceCents: 400,
    imageUrl: "/images/espresso.png",
    featured: true,
    available: true,
    tag: "House",
  },
  {
    slug: "flat-white",
    name: "Flat White",
    description: "Ristretto shots folded into silk milk. Compact, glossy, and precisely balanced.",
    category: "espresso",
    priceCents: 550,
    imageUrl: "/images/flatwhite.png",
    featured: false,
    available: true,
    tag: null,
  },
  {
    slug: "dark-mocha",
    name: "Dark Mocha",
    description: "70% single-origin chocolate melted into espresso and finished with a thin cream cap.",
    category: "espresso",
    priceCents: 675,
    imageUrl: "/images/mocha.png",
    featured: false,
    available: true,
    tag: null,
  },
  {
    slug: "yirgacheffe-pourover",
    name: "Yirgacheffe Pour-Over",
    description: "Floral Ethiopian lot brewed to order. Bergamot, wild honey, and jasmine on the nose.",
    category: "brew",
    priceCents: 700,
    imageUrl: "https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=800&q=80&auto=format&fit=crop",
    featured: true,
    available: true,
    tag: "Origin",
  },
  {
    slug: "house-cold-brew",
    name: "House Cold Brew",
    description: "Eighteen-hour steep. Low acid, dark cherry sweetness, served over a single clear cube.",
    category: "brew",
    priceCents: 575,
    imageUrl: "https://images.unsplash.com/photo-1461023058943-07fcbe16d735?w=800&q=80&auto=format&fit=crop",
    featured: true,
    available: true,
    tag: "All day",
  },
  {
    slug: "tasting-flight",
    name: "Tasting Flight",
    description: "Three 3oz pours of the current espresso, filter, and seasonal lot with tasting notes.",
    category: "brew",
    priceCents: 1400,
    imageUrl: "https://images.unsplash.com/photo-1507133750040-4a8f57021571?w=800&q=80&auto=format&fit=crop",
    featured: false,
    available: true,
    tag: "For two",
  },
  {
    slug: "ceremonial-matcha",
    name: "Ceremonial Matcha",
    description: "Stone-milled Uji matcha whisked to a fine foam. Bright, savory, and quietly sweet.",
    category: "seasonal",
    priceCents: 625,
    imageUrl: "https://images.unsplash.com/photo-1515823064-d6e0c04616a7?w=800&q=80&auto=format&fit=crop",
    featured: false,
    available: true,
    tag: "Seasonal",
  },
  {
    slug: "affogato",
    name: "Affogato",
    description: "Madagascar vanilla gelato drowned in a hot espresso. Dessert and digestif in one glass.",
    category: "seasonal",
    priceCents: 750,
    imageUrl: "https://images.unsplash.com/photo-1579954115545-a95591f28bfc?w=800&q=80&auto=format&fit=crop",
    featured: false,
    available: true,
    tag: "Dessert",
  },
  {
    slug: "butter-croissant",
    name: "Butter Croissant",
    description: "Laminated overnight with French butter. Shattering exterior, honeyed crumb.",
    category: "kitchen",
    priceCents: 450,
    imageUrl: "https://images.unsplash.com/photo-1555507036-ab1f4038024a?w=800&q=80&auto=format&fit=crop",
    featured: false,
    available: true,
    tag: "Baked at 6am",
  },
  {
    slug: "chocolate-morning-bun",
    name: "Chocolate Morning Bun",
    description: "A coiled bun of dark chocolate, orange zest, and toasted sugar. Made for the first coffee.",
    category: "kitchen",
    priceCents: 525,
    imageUrl: "https://images.unsplash.com/photo-1509365390695-33aee754301f?w=800&q=80&auto=format&fit=crop",
    featured: false,
    available: true,
    tag: null,
  },
  {
    slug: "corner-table-set",
    name: "Corner Table Set",
    description: "Aureum latte, butter croissant, and still water. The weekday ritual, composed.",
    category: "kitchen",
    priceCents: 1200,
    imageUrl: "https://images.unsplash.com/photo-1442512595331-e89e73853f31?w=800&q=80&auto=format&fit=crop",
    featured: false,
    available: true,
    tag: "Set",
  },
];

export async function ensureMenuSeeded() {
  const [existing] = await db.select({ value: count() }).from(menuItems);
  if ((existing?.value ?? 0) > 0) {
    return;
  }

  await db.insert(menuItems).values(catalog);
}
